Style improvements
Eliecer66/JSAPI pull request #2
Opened 2022-09-26 23:21 UTC by Eliecer66

This pull request is focus on the web page style. I restructure the some parts of the HTML and Css files, to make them more solid and easy enough to understand. I also added some responsive features.

2022-09-27 07:34 UTC, JorgEdmundo requested changes
Bro muy bien. Corrí el proyecto y se ve mucho mejor. Muy buena implementación sigue así. Te dejo unos comentarios, son sencillos. Los resuelves y estas listo para el siguiente PR. 💪

2022-09-27 07:34 UTC, JorgEdmundo commented on index.css
> +#idiomMenu {
```suggestion
#languageMenu {
```
Usa `language` idiom no es correcto.

2022-09-27 07:34 UTC, JorgEdmundo commented on index.html
>                  <select name="" id="idiomMenu">
```suggestion
                <select name="" id="languageMenu">
```

2022-09-27 07:34 UTC, JorgEdmundo commented on index.js
> +        console.log(data);
El `console.log` no debe estar en el código ya terminado. Esto es solo mientras estas haciendo pruebas y desarrollando.

2022-09-27 07:34 UTC, JorgEdmundo commented on index.js
> +        console.log(element.title);
Remover `console.log`

2022-09-27 07:34 UTC, JorgEdmundo commented on .gitignore
> +work-flow.md
Esto no es necesario ocultarlo. Es preferible que subas los archivos de documentación.

2022-09-27 07:34 UTC, JorgEdmundo commented on index.css
> +    max-width: 700px;
```suggestion
    max-width: 1400px;
    justify-content: space-between;
    padding: 30px 15px;
```

2022-09-27 07:34 UTC, JorgEdmundo commented on index.js
> +        element.style.backgroundImage = "url("+ ultimatePath +")";
`ultimatePath` no es un buen nombre para una variable. Que lleva dentro o que te trae esta URL? Trae la imagen. Entonces puede ser algo como `imageURL`, por darte una idea.

2022-09-27 16:17 UTC, Eliecer66 commented on .gitignore
> +work-flow.md
En ese archivo esta la API-Key por eso no lo subo

2022-09-28 06:56 UTC, JorgEdmundo requested changes

2022-09-28 06:56 UTC, JorgEdmundo commented on .gitignore
> +work-flow.md
Remove this.

2022-09-28 20:18 UTC, JorgEdmundo approved these changes
Muy bien Bro, buen trabajo. Ya lo puedes mergear. ✅

2022-09-28 20:58 UTC, merged