Render top movies
Eliecer66/JSAPI pull request #3
Opened 2022-09-28 01:53 UTC by Eliecer66

I added some new features like show the movies content inside a card.

2022-09-28 07:58 UTC, JorgEdmundo requested changes
Bro, buen PR. Corrí el código y el estilo esta muchísimo mejor, más limpio y mas bonito, muy bien hecho. Dos cosas importantes que hay que cambiar en este PR:
1. En el HTML no limites los resultados, imprime los 20. En caso que quieras limitar los resultados no lo haces en el HTML sino en el JS.
2. Refectoriza la función de top movies en dos, una que hace el fetch que es la auto-invocada (bien hecho ahí) y la otra que es la que renderiza.

Lo demás son comentarios sencillos. Muy buen trabajo.

2022-09-28 07:58 UTC, JorgEdmundo commented on .gitignore
> +work-flow.md
Elimina esta linea.

2022-09-28 07:58 UTC, JorgEdmundo commented on index.js
> +const pathCard = 'https://image.tmdb.org/t/p/w185'
```suggestion
const imageCardPath = 'https://image.tmdb.org/t/p/w185'
```

2022-09-28 07:58 UTC, JorgEdmundo commented on index.js
> +    let cardsList = document.getElementsByClassName('movieCard');
```suggestion
    const cardsList = document.getElementsByClassName('movieCard');
```

Es `const` porque no estás reasignando la variable.

2022-09-28 07:58 UTC, JorgEdmundo commented on index.js
> +const renderTopMovies = function() {
Así como hiciste en `renderResults` esto tienes que separarlo en dos functiones.
1. Hacer el `fetch` de los top movies.
2. Hacer la función que renderiza los top movies `renderTopMovies`.

2022-09-28 07:58 UTC, JorgEdmundo commented on index.js
> +        let i = 0;
Aquí llamarías tu función `renderTopMovies`.

2022-09-28 07:58 UTC, JorgEdmundo commented on index.js
> +        card.forEach(element => {
```suggestion
        card.forEach((element, index) => {
```
No necesitas la variable `i`, el segundo parametro del callback que recibe `forEach` es el index. Mira la [documentación](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach).

2022-09-28 07:58 UTC, JorgEdmundo commented on index.js
> +            let nameInfo = data.results[i].name || data.results[i].original_title  ;
```suggestion
            const posterPath = data.results[i].poster_path;
            const nameInfo = data.results[i].name || data.results[i].original_title  ;
```

2022-09-28 07:58 UTC, JorgEdmundo commented on index.js
> +            let imageUrl = pathCard+posterPath;
```suggestion
            const releaseInfo = data.results[i].first_air_date || data.results[i].release_date;
            const scoreInfo = data.results[i].vote_average.toFixed(1) * 10;
            const imageUrl = pathCard+posterPath;
```

2022-09-28 07:58 UTC, JorgEdmundo commented on index.js
> +            let box = element.children[1].children[2];
```suggestion
            const box = element.children[1].children[2];
```

2022-09-28 07:58 UTC, JorgEdmundo commented on index.js
> +            i++;
no necesitas esta variable.

2022-09-28 07:58 UTC, JorgEdmundo commented on index.js
> +    }
```suggestion
    const isAverage = value > regularScore && value < hightScore;
    const isHighScore = value > hightScore;
    const isBadScore = value < regularScore;
    
    if (isHighScore) {
        element.style.backgroundColor = '#58FA58';
    }
    if (isAverage) {
        element.style.backgroundColor = '#F3F781';
    }
    if (isBadScore) {
        element.style.backgroundColor = '#FA5858';
    }
```
Esto es un refactor de la función. Hay dos cosas importantes aquí:
1. Como ves no uso el `else if`, porque cuando esta anidado es incomodo de leer.
2. Las condiciones las moví a una variable. Esto hace la lectura sea mas fácil.

2022-09-28 07:58 UTC, JorgEdmundo commented on index.js
> +}();
Función auto invocada. Excelente! puntos positivos! Solo cambia el nombre de la función a algo como `loadTopMovies` y dentro de esta llamar tu `renderTopMovies`. Hacemos esto para que la aplicación sea "Modular" o por "Componentes". Es un principio importante.

2022-09-28 07:58 UTC, JorgEdmundo commented on index.html
> +        <div id="listContainer">
No, tu no limitas los resultados, tu imprimes todos los que te llegan, los 20. Igual a lo que hiciste con el del search.

2022-09-28 08:05 UTC, JorgEdmundo requested changes

2022-09-28 08:05 UTC, JorgEdmundo commented on index.js
> +const hightScore = 70;
```suggestion
const highScore = 70;
```
Usa este [Plugin](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) para evitar typos.

2022-10-02 11:03 UTC, JorgEdmundo requested changes
Muy buen trabajo. Puliendo un poco más los detalles. Prestar atención al uso y diferencia entre `let` y `const`. El top de películas, te comenté que no lo hicieras en un carousel. Igual la forma como hiciste el carousel te quedo cool, buen trabajo. Lo que vamos a hacer es que los resultados de la búsqueda no se muestren en un carousel.
Sigue así bro que vas cool.

2022-10-02 11:03 UTC, JorgEdmundo commented on .gitignore
> +work-flow.md
Haz pull de `master`. Asegúrate que esto se haya borrado.

2022-10-02 11:03 UTC, JorgEdmundo commented on index.css
> +    background:#0B173B ;
```suggestion
    background: #0B173B ;
```

2022-10-02 11:03 UTC, JorgEdmundo commented on index.css
> +.language, .singIn {
```suggestion
.language,
.singIn {
```
Como buena práctica, cuando usas comas, separas por lineas.

2022-10-02 11:03 UTC, JorgEdmundo commented on index.css
> +    display:none;
```suggestion
    display: none;
```

2022-10-02 11:03 UTC, JorgEdmundo commented on index.html
> +          <h2 id="title">New releases!</h2>
```suggestion
          <h2 class="title">New releases!</h2>
```
Esto es mejor manejarlo con una clase. El nombre `title` es generico y puede repetirse. Los `id` estan pensados para que sean únicos.

2022-10-02 11:03 UTC, JorgEdmundo commented on index.html
> +        <div id="titleContainer">
```suggestion
        <div class="titleContainer">
```
Esto es mejor manejarlo con una clase. El nombre `titleContainer` es generico y puede repetirse. Los id estan pensados para que sean únicos.

2022-10-02 11:03 UTC, JorgEdmundo commented on index.html
> +        <div id="listContainer"></div>
```suggestion
        <div id="topMoviesList"></div>
```
Que te parece este nombre?

2022-10-02 11:03 UTC, JorgEdmundo commented on index.js
> +        let imageUrl = path+result;
```suggestion
        const imageUrl = path+result;
```
Esta variable no la estás re-asignando. Igual sucede con las variables que están dentro de esta función.

2022-10-02 11:03 UTC, JorgEdmundo commented on index.js
> +        let imageUrl = path+data.belongs_to_collection.poster_path;
```suggestion
        const imageUrl = path+data.belongs_to_collection.poster_path;
```
Mismo comentario de arriba.

2022-10-02 11:03 UTC, JorgEdmundo commented on index.js
> +    const divContainer = document.getElementById('listContainer');
Este nombre es muy genérico. Busca uno mas a lo que estás haciendo. `topMoviesContainer` o algo así. Tu "código" debe "contar la historia" de lo que está sucediendo.

2022-10-02 11:03 UTC, JorgEdmundo commented on index.js
> +        const releaseInfo = element.first_air_date || element.release_date;
Me gustó esto. Puntos positivos.

2022-10-02 11:03 UTC, JorgEdmundo commented on index.js
> +        itemCard.children[0].style.backgroundImage = "url("+ imageUrl +")";
no uses `background` para la imagen. Usa el `<img />` tag.

2022-10-02 11:03 UTC, JorgEdmundo commented on index.js
> +            <div class="image"></div>
Usa el `<img />` tag con el `src`.

2022-10-02 11:03 UTC, JorgEdmundo commented on index.js
> +        console.log(data);
Siempre remover los `console.log`.

2022-10-03 15:41 UTC, Eliecer66 commented on index.html
> +          <h2 id="title">New releases!</h2>
Esto lo resolví en el ultimo pr que hice

2022-10-03 15:43 UTC, ilGiorgio commented on index.html
> +        <div id="titleContainer">
Esto también lo resolví en el último pr

2022-10-03 19:36 UTC, JorgEdmundo approved these changes

2022-10-03 19:37 UTC, merged